### ISSUE TITLE
Overhaul Walkthroughs and Guides

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#169]
Our guides and walkthroughs have fallen out of sync, so here's an overarching plan to realign them.

**The Guides**
- [x] An Iterative Walkthrough
   - [x] Guestbook (#170)
   - [x] Guestbook + Redis (#171)
   - [x] Guestbook + Redis + Consul (#172)
- [x] Terraform Beyond Layer0 (#173)
- [x] One-Off Tasks (#174)

**Comment by tlake** [comment]
I also think it would be helpful to strongly couple the names/groupings of our guides with directories in the examples repo. Something like:
- Change [layer0-examples repo]/guestbook to [layer0-examples repo]/iterative-walkthrough
- Change [layer0-examples repo]/guestbook-db to [layer0-examples repo]/terraform-beyond-layer0
- Does the One-Off Tasks guide need any material from the examples repo? If so, it might be a decent idea to make another directory for that guide in the examples repo.

**Comment by zpatrick** [comment]
tlake: the task walkthough should use this: https://github.com/quintilesims/layer0/blob/develop/tests/system/cases/task_performance/Dockerrun.aws.json

It's super simple, doesn't require managing our own image, and the command is configurable.

**Comment by zpatrick** [comment]
tlake: when you get to the consul + terraform part, let me know. the terraform part for consul is still WIP
